# version: '3.8'

services:
  cassandra:
    image: cassandra:4.1
    ports:
      - "9042:9042"
    environment:
      - CASSANDRA_CLUSTER_NAME=my_cluster
    volumes:
      - cassandra_data:/var/lib/cassandra
  init-cassandra:
    image: cassandra:4.1
    depends_on:
      - cassandra
    restart: "no"
    entrypoint: [ "/init.sh" ]
    volumes:
      - ./cassandra/init.sh:/init.sh
      - ./cassandra/init.cql:/docker-entrypoint-initdb.d/init.cql

  zookeeper:
    image: confluentinc/cp-zookeeper:7.0.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.0.0
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    volumes:
      - kafka_data:/var/lib/kafka/data

  core-functionality:
    build:
      context: .
      dockerfile: core-functionality/Dockerfile
    container_name: core-functionality
    depends_on:
      - cassandra
      - kafka
    ports:
      - "8081:8080"

  core-processor:
    build:
      context: .
      dockerfile: core-processor/Dockerfile
    container_name: core-processor
    depends_on:
      - cassandra
      - kafka
    ports:
      - "8082:8080"

  modula-platform:
    build:
      context: .
      dockerfile: modules/modula-platform/Dockerfile
    container_name: modula-platform
    depends_on:
      - cassandra
      - kafka
    ports:
      - "8083:8080"

volumes:
  cassandra_data:
  kafka_data: