spring:
  application:
    name: gateway

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000
  users:
    defaultUsers:
      admin:
        # admin: admin
        username: admin
        password: $2a$12$TPDXjh.Ci8uWiIv1pztl7O66Be9SkLdVFOw8bi6eoKQl8w2lt9Kfi
      user:
        # user: user
        username: user
        password: $2a$12$y09PMDXW1Um/eVFZyZ6T6O1MKsqGB3diUg0EBV0jL13rQtDcEAF.O
