spring:
  application:
    name: gateway

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000
  users:
    defaultUsers:
      admin:
        username: admin
        password: $2a$12$LQV1c1yqBWVHxkd0LHAkCOYz6TtxMQJqhN8/LewfT.qJp.6aVCwJS
      user:
        username: user
        password: $2a$12$LQV1c1yqBWVHxkd0LHAkCOYz6TtxMQJqhN8/LewfT.qJp.6aVCwJS
