server:
  port: 8082

spring:
  application:
    name: core-functionality
  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      group-id: ${spring.application.name}-group
      auto-offset-reset: earliest
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
  cassandra:
    keyspace-name: processes
    contact-points: cassandra:9042
    username: cassandra
    password: cassandra
    schema-action: CREATE_IF_NOT_EXISTS
    local-datacenter: datacenter1