server:
  port: 8082

spring:
  application:
    name: core-functionality
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: my-group
      auto-offset-reset: earliest
  cassandra:
    keyspace-name: my_keyspace
    contact-points: localhost
    port: 9042
    username: cassandra
    password: cassandra
    schema-action: CREATE_IF_NOT_EXISTS
    local-datacenter: datacenter1
  datasource:
    enabled: false
  jpa:
    enabled: false